---@diagnostic disable: undefined-global
require("mason").setup()
require("mappings")
require("plugins.neodev")
require("plugins.neotest")
require("plugins.dap")
require("plugins.dapui")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.treesitter")
require("plugins.lualine")
require("plugins.harpoon")
require("plugins.gitsigns")
require("plugins.tree")
require("plugins.telescope")
require("vim_settings")
require("transparency")
